name: Setup Storage

on:
    workflow_dispatch:

permissions:
    id-token: write

concurrency:
    group: release
    cancel-in-progress: false

jobs:
    setup:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout 🛎️
              uses: actions/checkout@main

            - name: Setup NodeJS
              uses: actions/setup-node@main
              with:
                  node-version: 20

            - name: Configure AWS credentials 🔑
              uses: aws-actions/configure-aws-credentials@main
              with:
                  role-to-assume: ${{ vars.AWS_ASSUME_ROLE_ARN }}
                  aws-region: ap-northeast-2

            - name: Setup Page
              id: spa
              uses: deploy-actions/s3-spa@v1
              with:
                  BucketName: resource.ddi-ing.com
                  Aliases: resource.ddi-ring.com
                  AcmCertificateArn: ${{ vars.RESOURCE_ACM }}
                  HostedZoneId: ${{ vars.HOSTEDZONEID }}
